### ISSUE TITLE
Sub-Categorization Of Wikis Is Reset When Reordering Wikis

### ISSUE THREAD

**Issue by orangiene** [humhub/wiki#224]
whenever I re-order a wiki that is already listed inside of a sub-category it causes that wiki to reset to being 'Pages without category'

see screenshots below

![wiki-before](https://user-images.githubusercontent.com/62644500/143270532-97965e8a-5b00-45df-b46b-a4dba238ee83.png)
![wiki-after](https://user-images.githubusercontent.com/62644500/143270546-0b275234-9cb9-4523-92fd-af68d4fc07a7.png)

**Comment by yurabakhtin** [comment]
@luke- @orangiene Fixed in PR https://github.com/humhub/wiki/pull/225.

**Comment by orangiene** [comment]
@yurabakhtin @luke-  do I need to reload something or update? The bug still exists in my installation :-(

**Comment by luke-** [comment]
@yurabakhtin Thanks!
